const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Candidate = sequelize.define('Candidate', {
  fullName: { type: DataTypes.STRING, allowNull: false },
  email: { type: DataTypes.STRING, allowNull: false },
  phoneNumber: { type: DataTypes.STRING },
  city: { type: DataTypes.STRING },
  zipCode: { type: DataTypes.STRING },
  english: { type: DataTypes.BOOLEAN, defaultValue: false },
  spanish: { type: DataTypes.BOOLEAN, defaultValue: false },
  creole: { type: DataTypes.BOOLEAN, defaultValue: false },
  other: { type: DataTypes.BOOLEAN, defaultValue: false },
  otherLanguage: { type: DataTypes.STRING },
  hasRBT: { type: DataTypes.STRING },
  rbtNumber: { type: DataTypes.STRING },
  hasMedicaid: { type: DataTypes.STRING },
  medicaidExpiration: { type: DataTypes.STRING },
  hasNPI: { type: DataTypes.STRING },
  npiNumber: { type: DataTypes.STRING },
  startImmediately: { type: DataTypes.STRING },
  startExplanation: { type: DataTypes.TEXT },
  morning: { type: DataTypes.BOOLEAN, defaultValue: false },
  afternoon: { type: DataTypes.BOOLEAN, defaultValue: false },
  exactHours: { type: DataTypes.STRING },
  reliableTransportation: { type: DataTypes.STRING },
  travelDistance: { type: DataTypes.STRING },
  yearsExperience: { type: DataTypes.STRING },
  preferredLocations: { type: DataTypes.STRING },
  age2to7: { type: DataTypes.BOOLEAN, defaultValue: false },
  age8to13: { type: DataTypes.BOOLEAN, defaultValue: false },
  age14to18: { type: DataTypes.BOOLEAN, defaultValue: false },
  pastCases: { type: DataTypes.TEXT },
  notesTimeliness: { type: DataTypes.STRING },
  understandRecoupment: { type: DataTypes.STRING },
  workedWithMedicaid: { type: DataTypes.STRING },
  driversLicense: { type: DataTypes.BOOLEAN, defaultValue: false },
  socialSecurity: { type: DataTypes.BOOLEAN, defaultValue: false },
  workAuthorization: { type: DataTypes.BOOLEAN, defaultValue: false },
  medicaidLetter: { type: DataTypes.BOOLEAN, defaultValue: false },
  ein: { type: DataTypes.BOOLEAN, defaultValue: false },
  einNumber: { type: DataTypes.STRING },
  startOnboarding: { type: DataTypes.STRING },
  bestContactTime: { type: DataTypes.STRING },
});

module.exports = Candidate;